apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ddbqbx4ak-python 
  janus-idp.io/tekton: ddbqbx4ak-python
  backstage.io/kubernetes-id: ddbqbx4ak-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ddbqbx4ak-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  