apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ddbqbx4ak-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ddbqbx4ak-python 
  name: ddbqbx4ak-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ddbqbx4ak-python 
